#!/usr/bin/env python3
"""
npz_to_c.py  —  convert one golden vector (.npz) into golden_vector.h

Usage:
    python npz_to_c.py golden_0.npz            # -> golden_vector.h
    python npz_to_c.py golden_0.npz -o gv.h

The .npz is expected to contain (any of these key spellings accepted):
    D   / D_q15   : int dictionary, shape (128, 256) or (256, 128)
    r   / residual: int residual,   shape (128,)
    idx / expected_idx / argmax : the golden argmax index (scalar)

Everything is emitted as int16 Q1.15. D is written ATOM-MAJOR as GV_D[N_ATOMS][M_LEN]
so the C side indexes GV_D[j][k] = atom j, element k — matching the engine's
contiguous per-atom read. No packing happens here; the C driver does the §7
two-values-per-word packing at load time (keeps one source of truth for layout).
"""
import argparse
import numpy as np

M_LEN = 128
N_ATOMS = 256


def pick(npz, names):
    for n in names:
        if n in npz:
            return npz[n]
    raise KeyError(f"none of {names} found in npz; keys are {list(npz.keys())}")


def as_atom_major(D):
    """Return D as (N_ATOMS, M_LEN) int array, atom-major (one atom per row)."""
    D = np.asarray(D)
    if D.shape == (M_LEN, N_ATOMS):        # measurement-major -> transpose
        D = D.T
    elif D.shape == (N_ATOMS, M_LEN):      # already atom-major
        pass
    else:
        raise ValueError(f"D shape {D.shape} is neither "
                         f"({M_LEN},{N_ATOMS}) nor ({N_ATOMS},{M_LEN})")
    return D


def check_q15(name, a):
    a = np.asarray(a)
    if a.min() < -32768 or a.max() > 32767:
        raise ValueError(f"{name} has values outside int16 range "
                         f"[{a.min()}, {a.max()}] — not Q1.15 ints. "
                         f"If these are floats, quantize first "
                         f"(round(x * 32768), clip to [-32768, 32767]).")
    return a.astype(np.int16)


def emit_2d(f, name, arr):
    rows, cols = arr.shape
    f.write(f"static const short {name}[{rows}][{cols}] = {{\n")
    for i in range(rows):
        vals = ",".join(str(int(v)) for v in arr[i])
        f.write(f"  {{{vals}}},\n")
    f.write("};\n\n")


def emit_1d(f, name, arr):
    n = arr.shape[0]
    vals = ",".join(str(int(v)) for v in arr)
    f.write(f"static const short {name}[{n}] = {{{vals}}};\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("npz")
    ap.add_argument("-o", "--out", default="golden_vector.h")
    args = ap.parse_args()

    z = np.load(args.npz)
    D = as_atom_major(pick(z, ["D", "D_q15", "dictionary"]))
    r = np.asarray(pick(z, ["r", "residual", "r_q15"])).reshape(-1)
    idx = int(np.asarray(pick(z, ["idx", "expected_idx", "argmax"])).reshape(-1)[0])

    if r.shape[0] != M_LEN:
        raise ValueError(f"residual length {r.shape[0]} != {M_LEN}")
    D = check_q15("D", D)
    r = check_q15("r", r)

    with open(args.out, "w") as f:
        f.write("/* Auto-generated by npz_to_c.py — do not edit. */\n")
        f.write(f"/* source: {args.npz} */\n")
        f.write("#ifndef GOLDEN_VECTOR_H\n#define GOLDEN_VECTOR_H\n\n")
        f.write(f"#define GV_EXPECTED_IDX {idx}\n\n")
        emit_2d(f, "GV_D", D)          # [N_ATOMS][M_LEN], atom-major
        emit_1d(f, "GV_R", r)          # [M_LEN]
        f.write("#endif /* GOLDEN_VECTOR_H */\n")

    print(f"wrote {args.out}: GV_D[{D.shape[0]}][{D.shape[1]}], "
          f"GV_R[{r.shape[0]}], GV_EXPECTED_IDX={idx}")


if __name__ == "__main__":
    main()